### ISSUE TITLE
Conversation Tree-Fitting Room, dialogue 14

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game-week1-old#398]
Is it possible to have the character name switch to Kyle for that specific dialogue?
![screen shot 2017-01-03 at 2 58 24 pm](https://cloud.githubusercontent.com/assets/22644654/21621013/2b6b41ee-d1c5-11e6-95c6-b003bb288b88.png)

**Comment by JSmith92** [comment]
Its in cyoa-data.js

**Comment by aarthyadityan** [comment]
Got this working. The issue now is that the background image still shows Donald. Should we change it? (maybe an empty room with an answering machine or something like that)

**Comment by JSmith92** [comment]
Sure i'll send Karina a request.
